apiVersion: apps/v1
kind: Deployment
metadata:
  name: soham-eta-deploy
  labels:
    app: soham-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: soham-eta-app
  template:
    metadata:
      labels:
        app: soham-eta-app
    spec:
      containers:
      - name: soham-eta-container
        image: 9733562315/k8deploy_demo_app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: soham-eta-np-service
  labels:
    app: soham-eta-app
spec:
  selector:
    app: soham-eta-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
